version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "" # Mot de passe vide
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Autoriser le mot de passe vide
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10


  eureka:
    build: ./eureka
    image: aziz/backend-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  gateway:
    build: ./gateway
    image: aziz/backend-gateway:latest
    container_name: gateway-service
    ports:
      - "8065:8065"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservices-network

  student-service:
    build:
      context: ./microservices/Student-Management-Microservice
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql-db
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/students
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data: