FROM openjdk:17
LABEL authors="Chayma"
EXPOSE 8005
ADD target/Room-Chambre-Management-Microservice-0.0.1-SNAPSHOT.jar Room-Chambre-Management-Microservice.jar
ENTRYPOINT ["java", "-jar", "Room-chambre-Management-Microservice.jar"]